### ISSUE TITLE
🐛 MCP error -32603: Tool execution failed: Error: self-signed certificate in certificate chain: Local Rancher K3S cluster

### ISSUE THREAD

**Issue by marcellodesales** [Flux159/mcp-server-kubernetes#91]
# Problem

* I have a local deployment of k3s Cluster running

```console
$ docker compose -f docker-compose-k8s.yaml ps
NAME         IMAGE                                                                 COMMAND                  SERVICE      CREATED      STATUS                    PORTS
kubernetes   dockerhub.docker.artifactory.company.com/rancher/k3s:v1.32.3-k3s1      "/bin/k3s server"        kubernetes   7 days ago   Up 14 minutes (healthy)   0.0.0.0:6443->6443/tcp
```

* As such, I can connect to it and run local tests of Operators, etc

```console
$ export KUBECONFIG=/Users/mdesales/dev/git.company.com/seceng-devsecops-platform/vionix-platform-aws-localstack/data/kubernetes/kubeconfig.yaml
$ kubectl get nodes
NAME           STATUS     ROLES                  AGE     VERSION
69600f095d70   Ready      control-plane,master   6d23h   v1.32.3+k3s1
ebfe1d86afd9   NotReady   control-plane,master   7d3h    v1.32.3+k3s1
```

* Its config is pointing to localhost

```console
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
```

# Problem: How to use the Kubernetes MCP Server to reach this server?

* The kubernetes instance is running in a local docker network, that is from a bridge

```console
$ docker compose -f docker-compose-k8s.yaml config
```
```yaml
....
networks:
  local-aws:
    name: local-aws
    external: true
```

* How to run the MCP server to run in a given local docker network?
  * That is, if the MCP Server is also in the same bridge network, it can have access to the server

# 📓 Notes from the thread

* The current version `0.1.0` loads the default `~/.kube/config` file always and caches it in memory
  * The suggestion could be to always receive the kubeconfig file via param to avoid the local cache on server bootstrap.

**Comment by Flux159** [comment]
When running the server, can you try using `NODE_TLS_REJECT_UNAUTHORIZED="0"` or try this in your kube config https://github.com/kubernetes-client/javascript/issues/7

**Comment by marcellodesales** [comment]
# 🔧 Bypass TLS from kubeconfig.yaml

* Attempted to change the file based on the configs as well

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRNd01UWTRNamN3SGhjTk1qVXdNekkyTVRreU1ESTNXaGNOTXpVd016STBNVGt5TURJMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRNd01UWTRNamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUekFDZ1d2dUNHRDFxd0hLMVRwdnVLSEhzS2VwSEF4ZDIraUVURXVGZFoKTWtHR0VkRElEU2dwbTE0QXB4L1RnRkI0eG50QzMwUkVtZS9FdVpHNWpXUmlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVThrZmJxMlhGMmlJZHJFWk0ydVIzClVZQ2hlZDR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYVhTQzhPRUJMVUgzUEorR2RzT0djRG1zWnRtM3Z3d0oKQWxFZlB0elNIZUFDSVFDVUN1UEd6Mm16TDZSUlVuK2w3djdDU2RjNzQ1RCtsN09vM2dJVzM1aElOQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJS0prQ2ZTa2I1VWd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelF6TURFMk9ESTNNQjRYRFRJMU1ETXlOakU1TWpBeU4xb1hEVEkyTURNeQpOakU1TWpBeU4xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQbFpTaFFJaTdIS3VHZ0kKTmtoS1RSVURjMVpYak5SQkxXMU9ZS2tuOEptY0NLbXM1L2Y1dDhNOHcvVjZXOHAzYW1TeEJBZGVzT0dUdG1yLwo5M0QrOFBHalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUUl1NC9GMTZ2ckN1aUFMb2ZOKy9FSTVwZC9uREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQTNudTREU2dnOXBJWWZsUlZGZktxSzQxWGVPMmVIS1A2Y05mK0xhS004b3dDSUVLQzUvN0doL0cvemlpUQprd3g2ZXpMRGIybU52cU9xbHAxaUpnL01DWWllCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTkRNd01UWTRNamN3SGhjTk1qVXdNekkyTVRreU1ESTNXaGNOTXpVd016STBNVGt5TURJMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTkRNd01UWTRNamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSZzlzY28va0F2YW9wWFB0MEcxaCtSQTZ6azNPY1JuaUJLQnBaajNiQ2MKcXkwSUdrUW1wK1NuS0NXamlWQkdoRGtBSGVHVCsvUTRCR2RNak90V2VLZDZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNMdVB4ZGVyNndyb2dDNkh6ZnZ4CkNPYVhmNXd3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnUVRnZnNmM09mcW5zdmd4UTUrcFlVb1Rob3lzdDAyVnUKL29obi81YXdWTTRDSUhsK0xvOEJuSy9BTGkrc1NjZ2J4SXZVNzZXQ204OHlpMGtwRWdzb1I5dGoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUx6c3RiMEF4ZWtrK05FVnZRQ2g3R2FPYkZtZEJZNlNXL2l5MVJrSmo3MTVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFK1ZsS0ZBaUxzY3E0YUFnMlNFcE5GUU56VmxlTTFFRXRiVTVncVNmd21ad0lxYXpuOS9tMwp3enpEOVhwYnluZHFaTEVFQjE2dzRaTzJhdi8zY1A3dzhRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```

* It has failed

```console
{}
Error executing code: MCP error -32603: MCP error -32603: Tool execution failed: Error: self-signed certificate in certificate chain
```

# ✍ Manually verifying

* Testing it locally also failed with the config setting... 

```console
$ kubectl get namespaces
error: specifying a root certificates file with the insecure flag is not allowed
```

* Then, removing the certificate-data made it working locally

```console
$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   7d15h
kube-node-lease   Active   7d15h
kube-public       Active   7d15h
kube-system       Active   7d15h
```

# ❓ Questions

* Does Claude map the file-system to /projects and creates a copy of the files? 
  * Somehow the docker volume mapping works, but it doesn't see any changes to the file (Seems like it)
  * I will further confirm, but I'm running out of free messages

This is my `claude_desktop_config.json` currently

```json
{
  "mcpServers": {
    "filesystem": {
      "command": "docker",
      "args": [
        "run",
        "-i",
        "--rm",
        "--mount", "type=bind,src=/Users/mdesales/dev,dst=/projects/dev",
        "mcp/filesystem",
        "/projects"
      ]
    },
    "kubernetes": {
      "command": "npx",
      "args": ["mcp-server-kubernetes"]
    }
  }
}
```
